#!/usr/bin/env bash

paths=(
  # ".config/"

)

for p in "${paths[@]}"; do
  mkdir -p "$HOME/archlinux/$(dirname "$p")"
  mv "$HOME/$p" "$HOME/archlinux/$p"
  ln -sfn "$HOME/archlinux/$p" "$HOME/$p"
done

# ------------------------------------------------

fd -H -t l -E 'archlinux/*' . "$HOME" | while IFS= read -r f; do
    target=$(readlink -f "$f")
    case "$target" in
        "$HOME"/archlinux/*) ;;
        *) continue ;;
    esac

    if [ ! -e "$f" ]; then
      rm -rf "$f"
      continue
    fi
    if [ -d "$f" ] && [ -z "$(fd -H . "$f" -L --max-depth 1)" ]; then
      rm -rf "$f" "$target"
      continue
    fi
    echo "$f"
  done | sed "s|^$HOME/||" > "$HOME/archlinux/symlinks"

# ------------------------------------------------

yay -Syu --noconfirm

pacman -Qqen > "$HOME/archlinux/pacman.packages"
pacman -Qqem > "$HOME/archlinux/yay.packages"

roots=(
  # ~/projects
  ~/.src
)
find "${roots[@]}" -name .git -type d -print0 | while IFS= read -r -d '' d; do
  repo="${d%/.git}"
  echo "==> $repo"
  git -C "$repo" fetch origin
  git -C "$repo" reset --hard "origin/$(git -C "$repo" symbolic-ref --short HEAD)"
  git -C "$repo" pull
done
