#!/usr/bin/env bash

yay -Syu --noconfirm                # full system + AUR upgrade
yay -Rns $(yay -Qtdq) --noconfirm   # remove orphaned packages
yay -Sc --noconfirm                 # clean package cache

roots=(
  # ~/projects
  ~/.src
)
find "${roots[@]}" -name .git -type d -print0 | while IFS= read -r -d '' d; do
  repo="${d%/.git}"
  echo "==> $repo"
  git -C "$repo" fetch origin
  git -C "$repo" reset --hard "origin/$(git -C "$repo" symbolic-ref --short HEAD)"
  git -C "$repo" pull
done

repos=(
  "$HOME/hw"
  "$HOME/archlinux"
  "$HOME/personal/profile"
)

for repo in "${repos[@]}"; do
  echo "==> $repo"
  git -C "$repo" add -A
  git -C "$repo" commit -m "chore: automated update"
  git -C "$repo" push origin main
done

# ------------------------------------------------

fd -H -t l -E 'archlinux/*' . "$HOME" | while IFS= read -r f; do
    target=$(readlink -f "$f")
    case "$target" in
        "$HOME"/archlinux/*) ;;
        *) continue ;;
    esac
    if [ ! -e "$f" ]; then
      rm -rf "$f"
      continue
    fi
    if [ -d "$f" ] && [ -z "$(fd -H . "$f" -L --max-depth 1)" ]; then
      rm -rf "$f" "$target"
      continue
    fi
    echo "$f"
  done | sed "s|^$HOME/||" > "$HOME/archlinux/symlinks"

pacman -Qqen > "$HOME/archlinux/pacman.packages"
pacman -Qqem > "$HOME/archlinux/yay.packages"

# ------------------------------------------------

USB="/run/media/iqrar/IQRAR_USB"
if [ -e "$USB" ]; then
  rm -rf "$USB/personal"
  cp -r "$HOME/personal" "$USB"
fi
