close_on_child_death yes
confirm_os_window_close 0
listen_on unix:@mykitty
allow_remote_control yes
enable_audio_bell no
scrollback_lines 0
paste_actions quote-urls-at-prompt,replace-dangerous-control-codes,confirm-if-large
strip_trailing_spaces always
copy_on_select clipboard
clipboard_control write-clipboard write-primary read-clipboard read-primary
font_family JetBrainsMono Nerd Font
font_size 9.3
clear_all_shortcuts yes

map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
map ctrl+0 change_font_size all 0
map ctrl+shift+v paste_from_clipboard

map shift+enter send_text all \x1b[13;2u
map ctrl+alt+1 send_text all \x1b[49;7u
map ctrl+alt+2 send_text all \x1b[50;7u
map ctrl+alt+3 send_text all \x1b[51;7u
map ctrl+alt+4 send_text all \x1b[52;7u
map ctrl+alt+5 send_text all \x1b[53;7u
map ctrl+alt+6 send_text all \x1b[54;7u

mouse_map left click grabbed,ungrabbed mouse_handle_click selection link prompt
mouse_map middle press grabbed,ungrabbed mouse_selection rectangle
mouse_map right press grabbed,ungrabbed mouse_selection drag_or_normal_select

map ctrl+b>y>p kitten hints --type=word --program=-
map ctrl+b>y>y kitten hints --type=word --program=@
