close_on_child_death yes
confirm_os_window_close 0
listen_on unix:@mykitty
allow_remote_control yes
term xterm-kitty
env TERM_PROGRAM=kitty
env COLORTERM=truecolor
enable_audio_bell no
file_transfer_confirmation_bypass 5

scrollback_lines 0
mouse_hide_wait 1
input_delay 3
repaint_delay 10
sync_to_monitor no
remember_window_size no
initial_window_width 1800
initial_window_height 1200
placement_strategy top-left
hide_window_decorations yes

paste_actions quote-urls-at-prompt,replace-dangerous-control-codes,confirm-if-large
strip_trailing_spaces always
copy_on_select clipboard
clipboard_control write-clipboard write-primary read-clipboard read-primary
detect_urls yes
allow_hyperlinks yes
include ~/archlinux/.config/kitty/current-theme.conf

shell_integration no-cursor
cursor_blink_interval -1
cursor_stop_blinking_after 0
font_family JetBrainsMono Nerd Font
font_size 9.4
disable_ligatures never
cursor_shape beam
default_pointer_shape beam
cursor_beam_thickness 1.5
cursor_underline_thickness 2.0

clear_all_shortcuts yes
clear_all_mouse_actions yes

map ctrl+equal change_font_size all +2.0
map ctrl+minus change_font_size all -2.0
map ctrl+0 change_font_size all 0
map ctrl+shift+v paste_from_clipboard

map shift+enter send_text all \x1b[13;2u
# Shift+Alt+Ctrl+Home
map alt+enter send_text all \x1b[1;8H
map ctrl+backspace send_text all \x1b[127;5u
# Shift+Alt+Ctrl+Left
map ctrl+enter send_text all \x1b[1;8D
# Shift+Alt+Ctrl+Right
map ctrl+shift+g send_text all \x1b[1;8C
# Shift+Alt+Ctrl+Down
map ctrl+shift+i send_text all \x1b[1;8B
# Shift+Alt+Ctrl+Up
map ctrl+shift+x send_text all \x1b[1;8A
# Shift+Alt+Ctrl+PageDown
map ctrl+comma send_text all \x1b[6;8~
# Shift+Alt+Ctrl+D
map alt+escape send_text all \x1b[100;8u

mouse_map left click grabbed,ungrabbed mouse_handle_click selection link prompt
mouse_map middle press grabbed,ungrabbed mouse_selection rectangle
mouse_map right press grabbed,ungrabbed mouse_selection drag_or_normal_select

action_alias myhints kitten hints --alphabet efhadlscvmnrtwpoijgb,qxuyk-{}[]_=()<>+.?~#*^&`@!\"$\'%EFHADLSCVMNRTWPOIJGBQXUYK

map ctrl+b>y>j myhints --type=word --program=-
map ctrl+b>y>k myhints --type=word --program=@
map ctrl+b>y>l myhints --type=hyperlink --program=default
