set -g theme detect

# DARK COLORS
set -g dark-theme-black       "#181825"
set -g dark-theme-white       "#cdd6f4"
set -g dark-theme-light-grey  "#a6adc8"
set -g dark-theme-dark-grey   "#313244"
set -g dark-theme-green       "#2e465e"
set -g dark-theme-yellow      "#C2B08C"
set -g dark-theme-red         "#1e1e2e"
set -g dark-theme-blue        "#89b4fa"
set -g dark-theme-cyan        "#cdd6f4"
set -g dark-theme-magenta     "#2e465e"

# LIGHT COLORS
set -g light-theme-black       "#eff1f5"
set -g light-theme-white       "#4c4f69"
set -g light-theme-light-grey  "#6c6f85"
set -g light-theme-dark-grey   "#dce0e8"
set -g light-theme-green       "#cbefc8"
set -g light-theme-yellow      "#df8e1d"
set -g light-theme-red         "#eff1f5"
set -g light-theme-blue        "#1e66f5"
set -g light-theme-cyan        "#4c4f69"
set -g light-theme-magenta     "#eff1f5"

set -g pane-border-style "fg=themedarkgrey"
set -g pane-active-border-style "fg=themeblue"
set -g status-style "fg=themelightgrey,bg=themeblack"
set -g message-style "fg=themered,bg=themeyellow,bold"
set -g mode-style "bg=themegreen"
setw -g window-status-style "fg=themelightgrey,bg=themeblack"
setw -g window-status-current-style "fg=themered,bg=themeblue,bold"
setw -g window-status-activity-style "fg=themewhite,bg=themeblack,underscore"
set -g status-left "#[fg=themered,bg=themeyellow,bold] #S #[fg=themelightgrey,bg=themeblack,none]"
