bind-key y switch-client -T my-table
bind-key -T my-table a display-popup -E -w 100% -h 100% -B "~/archlinux/.config/tmux/bin/which-key"
bind-key -T my-table b run-shell -b "~/archlinux/.config/tmux/bin/reload-kitty"
bind-key -T my-table c new-window -c "#{pane_current_path}"
bind-key -T my-table y run-shell -b "tmux set-buffer '#{pane_current_path}' && tmux save-buffer - | wl-copy"
bind-key -T my-table r run-shell "tmux source ~/.config/tmux/tmux.conf" \; display-message "tmux.conf sourced"

bind-key -T my-table s run-shell -b "~/archlinux/.config/tmux/bin/capture-prompt current"
bind-key -T my-table enter run-shell -b "~/archlinux/.config/tmux/bin/capture-prompt previous"
bind-key -T my-table a run-shell -b "~/archlinux/.config/tmux/bin/capture-context view"
bind-key -T my-table d run-shell -b "~/archlinux/.config/tmux/bin/capture-context buffer"

bind -T copy-mode-vi y send-keys -X copy-selection
bind -T copy-mode-vi c send-keys -X copy-pipe-and-cancel
bind -T copy-mode-vi p send-keys -X copy-pipe-and-cancel "tmux paste-buffer -p"
bind -T copy-mode-vi d send-keys -X copy-pipe-and-cancel "hyprctl dispatch 'hl.dsp.focus({ workspace = \"1\" })' >/dev/null \
  && ~/archlinux/.config/hypr/bin/paste"

# ------------------------------------------------

bind-key -r & kill-window
bind-key -r x kill-pane

bind -T copy-mode-vi v send-keys -X begin-selection
bind -T copy-mode-vi C-v send-keys -X begin-selection \; send-keys -X rectangle-toggle

bind C-End copy-mode \; send-keys -X history-bottom
bind C-Home copy-mode \; send-keys -X history-top
bind -T copy-mode-vi C-Home send-keys -X history-top
bind -T copy-mode-vi C-End  send-keys -X history-bottom

set -g allow-passthrough all
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"
set -g mouse on
set -g base-index 1
setw -g pane-base-index 1
set -g history-limit 5000
set -q -g status-utf8 on
setw -q -g utf8 on
set -sg escape-time 1
set -g status-keys vi
set -g mode-keys vi
set -g monitor-activity on
set -g visual-activity off
set -g extended-keys on
set -g renumber-windows on
set -g status off

set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'
set -g @continuum-restore 'on'
set -g @resurrect-capture-pane-contents 'on'

# git clone https://github.com/tmux-plugins/tpm ~/.tmux/plugins/tpm
run '~/.tmux/plugins/tpm/tpm'
