# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap-default.toml
[mgr]

prepend_keymap = [
  # https://github.com/boydaihungst/gvfs.yazi
  { on = [ "M", "m" ], run = "plugin gvfs -- select-then-mount --jump", desc = "Select device to mount and jump to its mount point" },
  { on = [ "M", "R" ], run = "plugin gvfs -- remount-current-cwd-device", desc = "Remount device under cwd" },
  { on = [ "M", "u" ], run = "plugin gvfs -- select-then-unmount", desc = "Select device then unmount" },
  { on = [ "M", "U" ], run = "plugin gvfs -- select-then-unmount --eject", desc = "Select device then eject" },
  { on = [ "M", "a" ], run = "plugin gvfs -- add-mount", desc = "Add a GVFS mount URI" },
  { on = [ "M", "e" ], run = "plugin gvfs -- edit-mount", desc = "Edit a GVFS mount URI" },
  { on = [ "M", "r" ], run = "plugin gvfs -- remove-mount", desc = "Remove a GVFS mount URI" },
  { on = [ "g", "m" ], run = "plugin gvfs -- jump-to-device", desc = "Select device then jump to its mount point" },
  { on = [ "`", "`" ], run = "plugin gvfs -- jump-back-prev-cwd", desc = "Jump back to the position before jumped to device" },
  { on = [ "M", "t" ], run = "plugin gvfs -- automount-when-cd", desc = "Enable automount when cd to device under cwd" },
  { on = [ "M", "T" ], run = "plugin gvfs -- automount-when-cd --disabled", desc = "Disable automount when cd to device under cwd" },

  { on = [ "g", "i" ], run = '''shell 'bash ~/archlinux/.config/yazi/bin/goto-mtp "Internal storage/Documents/"' --confirm''', desc = "Go to MTP: Internal storage" },
  { on = [ "g", "w" ], run = '''shell 'bash ~/archlinux/.config/yazi/bin/goto-mtp "Internal storage/Android/media/com.whatsapp/WhatsApp/Media/WhatsApp Documents"' --confirm''', desc = "Go to MTP: WhatsApp Documents" },
	{ on = [ "g", "s" ], run = "reveal ~/archlinux/.config/", desc = "Go to ~/archlinux" },
	{ on = [ "g", "u" ], run = "reveal /run/media/iqrar/IQRAR_USB/personal/phone/", desc = "Go to IQRAR_USB: personal" },
	{ on = [ "g", "l" ], run = "reveal ~/.local/share/", desc = "Go to ~/.local" },
	{ on = [ "g", "p" ], run = "reveal ~/personal/phone/", desc = "Go to ~/personal" },

	{ on = [ "<Space>", "o" ], run = "open --hovered",               desc = "Always open the hovered file" },
	{ on = [ "<Space>", "O" ], run = "open --interactive --hovered", desc = "Open hovered file interactively" },
	{ on = [ "<Space>", "d" ],  run = "remove --hovered",                       desc = "Trash the hovered file only" },
	{ on = [ "<Space>", "D" ],  run = "remove --permanently --hovered",         desc = "Permanently delete the hovered file only" },
	{ on = [ "<Space>", "r" ],      run = "rename --hovered --cursor=before_ext", desc = "Always rename the hovered file" },
	{ on = [ "<Space>", "a" ], run = "create --force",            desc = "Create, overwrite destination without confirmation" },
	{ on = [ "<Space>", "p" ], run = "paste --follow",         desc = "Paste, copying symlink targets rather than the links" },
	{ on = [ "<Space>", "P" ], run = "paste --force --follow", desc = "Paste, overwrite destination and copy symlink targets" },

	{ on = [ "<Space>", "c", "c" ], run = "copy path --hovered",             desc = "Copy hovered path" },
	{ on = [ "<Space>", "c", "C" ], run = "copy url --hovered",              desc = "Copy hovered URL" },
	{ on = [ "<Space>", "c", "d" ], run = "copy dirpath --hovered",          desc = "Copy hovered directory path" },
	{ on = [ "<Space>", "c", "D" ], run = "copy dirurl --hovered",           desc = "Copy hovered directory URL" },
	{ on = [ "<Space>", "c", "f" ], run = "copy filename --hovered",         desc = "Copy hovered filename" },
	{ on = [ "<Space>", "c", "n" ], run = "copy name_without_ext --hovered", desc = "Copy hovered filename without extension" },

  { on = [ "F" ], run = 'search_do --via=fd --args=', desc = "Flat view" },

	{ on = "<Tab>", run = [ "toggle", "arrow 1" ], desc = "Toggle the current selection state" },
	{ on = "<S-Tab>", run = [ "toggle", "arrow -1" ], desc = "Toggle the current selection state" },

	{ on = "^", run = "spot", desc = "Spot hovered file" },
]

[input]

prepend_keymap = [
	{ on = "X", run = [ "delete --cut", "move -1 --in-operating" ],         desc = "Cut current character" },
  { on = [ "\"", "H", "d" ], run = "delete",                              desc = "Delete selected characters without cutting to clipboard" },
  { on = [ "\"", "H", "D" ], run = [ "delete", "move eol" ],               desc = "Delete until EOL without cutting" },
  { on = [ "\"", "H", "c" ], run = [ "delete", "--insert" ],               desc = "Delete and enter insert mode without cutting" },
  { on = [ "\"", "H", "C" ], run = [ "delete --insert", "move eol" ],      desc = "Delete until EOL and enter insert mode without cutting" },
  { on = [ "\"", "H", "x" ], run = [ "delete", "move 1 --in-operating" ],  desc = "Delete current character without cutting" },
  { on = [ "\"", "H", "X" ], run = [ "delete", "move -1 --in-operating" ],  desc = "Delete current character without cutting" },

	{ on = "<S-Home>",         run = "kill bol",      desc = "Kill backwards to the BOL" },
	{ on = "<S-End>",         run = "kill eol",      desc = "Kill forwards to the EOL" },
]

[cmp]

prepend_keymap = [
	{ on = "<A-C-S-Home>",   run = "close --submit",                             desc = "Submit the completion" }, # default
	{ on = "<C-c>", run = [ "close", "input:close" ], desc = "Complete and submit the input" }, # default

  { on = "<S-Tab>", run = "arrow prev", desc = "Previous item" }, # default
	{ on = "<Tab>", run = "arrow next", desc = "Next item" }, # default
]
