# https://github.com/sxyazi/yazi/blob/main/yazi-config/preset/keymap-default.toml
[mgr]

prepend_keymap = [
  # https://github.com/boydaihungst/gvfs.yazi
  { on = [ "M", "m" ], run = "plugin gvfs -- select-then-mount --jump", desc = "Select device to mount and jump to its mount point" },
  { on = [ "M", "R" ], run = "plugin gvfs -- remount-current-cwd-device", desc = "Remount device under cwd" },
  { on = [ "M", "u" ], run = "plugin gvfs -- select-then-unmount", desc = "Select device then unmount" },
  { on = [ "M", "U" ], run = "plugin gvfs -- select-then-unmount --eject", desc = "Select device then eject" },
  { on = [ "M", "a" ], run = "plugin gvfs -- add-mount", desc = "Add a GVFS mount URI" },
  { on = [ "M", "e" ], run = "plugin gvfs -- edit-mount", desc = "Edit a GVFS mount URI" },
  { on = [ "M", "r" ], run = "plugin gvfs -- remove-mount", desc = "Remove a GVFS mount URI" },
  { on = [ "g", "m" ], run = "plugin gvfs -- jump-to-device", desc = "Select device then jump to its mount point" },
  { on = [ "`", "`" ], run = "plugin gvfs -- jump-back-prev-cwd", desc = "Jump back to the position before jumped to device" },
  # automount-when-cd is not designed for mtp://
  { on = [ "M", "t" ], run = "plugin gvfs -- automount-when-cd", desc = "Enable automount when cd to device under cwd" },
  { on = [ "M", "T" ], run = "plugin gvfs -- automount-when-cd --disabled", desc = "Disable automount when cd to device under cwd" },

  { on = [ "g", "i" ], run = '''shell 'bash ~/archlinux/.config/yazi/bin/goto-mtp "Internal storage/Documents/"' --confirm''', desc = "Go to MTP: Internal storage" },
  { on = [ "g", "w" ], run = '''shell 'bash ~/archlinux/.config/yazi/bin/goto-mtp "Internal storage/Android/media/com.whatsapp/WhatsApp/Media/WhatsApp Documents"' --confirm''', desc = "Go to MTP: WhatsApp Documents" },
	{ on = [ "g", "s" ], run = "reveal ~/archlinux/.config/", desc = "Go to ~/archlinux" },
	{ on = [ "g", "u" ], run = "reveal /run/media/iqrar/IQRAR_USB/personal/phone/", desc = "Go to IQRAR_USB: personal" },
	{ on = [ "g", "l" ], run = "reveal ~/.local/share/", desc = "Go to ~/.local" },
	{ on = [ "g", "p" ], run = "reveal ~/personal/phone/", desc = "Go to ~/personal" },

	# Toggle
	{ on = "<Tab>", run = [ "toggle", "arrow 1" ], desc = "Toggle the current selection state" },
	{ on = "<S-Tab>", run = [ "toggle", "arrow -1" ], desc = "Toggle the current selection state" },

	# Spotting
	{ on = "<Space>", run = "spot", desc = "Spot hovered file" },
]

[input]

prepend_keymap = [

  # Kill
	{ on = "<S-Home>",         run = "kill bol",      desc = "Kill backwards to the BOL" },
	{ on = "<S-End>",         run = "kill eol",      desc = "Kill forwards to the EOL" },
]
