[ids]
*

[main]
f21 = wlan
sysrq = M-A-C-S-s
home = volumedown
end = volumeup
` = M-A-C-S-t
1 = M-A-C-S-j
2 = -
3 = [
4 = ]
7 = layer(my_seven)
8 = layer(mini_pairs)
9 = {
0 = }
- = _
t = m
y = enter
[ = capslock
] = ^
capslock = /
a = t
g = y
h = a
j = h
k = j
l = k
; = l
' = layer(my_quote)
\ = layer(altgr)
enter = layer(shift)
leftshift = layer(my_left_shift)
102nd = M-A-C-S-w
n = g
m = escape
, = n
. = ,
rightshift = layer(my_right_shift)
control = layer(alt)
leftmeta = layer(shift)
leftalt = layer(meta)
rightalt = layer(control)

[control]
` = M-A-C-S-v
2 = C-=
3 = C-s
4 = C-h
9 = C-k
0 = C-]
- = C-S-u
] = C-d
capslock = A-C-s

e = C-S-z
t = C-t
y = C-y
u = A-9
i = C-z
p = C-i
a = C-a
s = C-l
d = A-C-7
g = C-g
h = A-enter
j = A-1
k = A-2
l = A-3
; = A-4
leftshift = M-C-S-d
z = C-e
b = ~
n = C-j
m = A-C-c
, = A-C-d
. = A-C-a

[alt]
2 = C-0
3 = A-l
4 = A-h
9 = A-k
0 = A-j
] = A-C-y
capslock = A-C-b
e = A-y
t = A-t
i = A-z
a = A-a
g = A-g
h = A-S-enter
z = A-e
n = A-i
, = A-n
. = A-m
j = A-5
k = A-6
l = A-7
; = A-8

[shift]
` = M-A-C-S-r
2 = @
3 = "
4 = !
9 = $
0 = `
- = %
] = '
capslock = \
. = ;
m = :
leftshift = M-C-S-c
space = delete

[control+shift]
2 = A-C-m
3 = C-S-s
4 = C-S-h
9 = A-C-g
0 = C-enter
- = A-C-f
] = A-C-S-end
enter = layer(alt)
w = A-C-l
e = A-C-p
u = C-S-enter
i = A-C-n
s = A-C-e
d = A-C-h
g = C-S-g
h = C-u
j = C-S-e
k = C-S-j
l = C-S-k
; = C-S-l
z = C-S-i
b = C-S-b
n = C-p
m = C-S-w
, = C-S-n
. = A-C-S-pageup

[alt+shift]
w = M-A-C-S-g
e = M-A-C-S-h
r = M-A-C-S-i
a = macro( C-home 80ms C-v 80ms C-S-end 80ms delete )
s = C-delete
d = C-backspace
f = macro( S-end 30ms delete )
j = A-S-e
k = A-S-j
l = A-S-k
; = A-S-l
z = A-S-]
c = macro( home 30ms S-end 30ms delete 30ms backspace )
v = macro( S-home 30ms backspace )

[alt+control+shift]
s = A-C-o
d = A-C-u

[meta]
` = M-A-C-S-n
1 = M-A-C-S-k
2 = =
3 = <
4 = >
6 = M-A-C-S-m
9 = (
0 = )
- = +
q = 1
w = 2
e = 3
r = 4
t = 5
y = 6
u = 7
i = 8
o = 9
p = 0
] = &
capslock = |
a = left
s = up
d = down
f = right
g = middlemouse
h = .
j = home
k = pagedown
l = pageup
; = end
leftshift = M-c
z = #
c = rightmouse
v = leftmouse
b = ?
m = scrolldown
n = scrollup
, = *
. = C-b
space = backspace

[meta+control]
# M-1,3,4,5,8 are the only ones suited for app switch shortcuts
2 = C--
- = A-C-k
q = M-A-C-S-e
w = M-5
e = C-left
r = C-right
t = A-C-z
u = M-6
i = C-down
o = C-up
p = M-A-C-S-d
] = M-A-C-S-l
capslock = A-C-S-s
a = C-home
s = C-pageup
d = C-pagedown
f = C-end
# j = M-A-C-a
# k = M-A-C-z
# l = M-A-C-y
# ; = M-A-C-r
j = M-1
k = M-2
l = M-3
; = M-4
v = M-A-C-t

[meta+shift]
k = S-end
; = S-pagedown
m = scrollleft
n = scrollright

[meta+alt]
q = kp0
capslock = A-C-S-b
a = A-left
j = A-home
k = A-end
l = A-pageup
; = A-pagedown

[meta+control+shift]
s = C-S-pageup
d = C-S-pagedown
e = C-S-left
r = C-S-right
w = M-S-5
i = C-S-down
o = C-S-up
j = M-S-1
k = M-S-2
l = M-S-3
; = M-S-4

[my_quote]
q = M-A-C-S-a
w = M-A-C-S-b
e = M-A-C-S-f
r = M-A-C-S-c
t = M-A-C-S-q
g = C-leftmouse
z = A-leftmouse
x = C-S-leftmouse
c = macro( leftmouse 50ms leftmouse 50ms leftmouse )
v = macro( leftmouse 50ms leftmouse )

[my_right_shift]
t = A-C-6
a = A-C-4
s = A-C-1
d = A-C-2
f = A-C-5
g = A-C-3

[my_left_shift]
j = M-left
k = M-down
l = M-up
; = M-right

[mini_pairs]
w = macro( ` 10ms ` 10ms left )
e = macro( - 10ms - 10ms left )
r = macro( _ 10ms _ 10ms left )
a = macro( < 10ms > 10ms left )
s = macro( [ 10ms ] 10ms left )
d = macro( ( 10ms ) 10ms left )
f = macro( { 10ms } 10ms left )
g = macro( " 10ms " 10ms left )
x = macro( * 10ms * 10ms left )
c = macro( delete 10ms backspace )
v = macro( ' 10ms ' 10ms left )
space = macro( space 10ms space 10ms left )

[my_seven]
5 = M-A-C-S-p
6 = M-A-C-S-o
8 = macro( 5 30ms 4 30ms 0 30ms 7 30ms 2 30ms 5 )
9 = M-A-C-S-u
