[ids]
*

[main]
f21 = wlan
sysrq = M-A-C-S-s
home = volumedown
end = volumeup
` = M-A-C-S-t
1 = M-A-C-S-j
2 = -
3 = [
4 = ]
8 = ^
7 = layer(mini_pairs)
9 = {
0 = }
- = _
t = m
y = enter
[ = capslock
capslock = /
a = t
g = y
h = a
j = h
k = j
l = k
; = l
' = layer(my_mouse)
\ = layer(altgr)
enter = layer(shift)
102nd = M-A-C-S-w
n = g
m = escape
, = n
. = ,
rightshift = layer(my_right_shift)
control = layer(alt)
leftmeta = layer(shift)
leftalt = layer(meta)
rightalt = layer(control)

[control]
9 = A-1
0 = A-2
- = A-3
y = A-enter
b = A-7
m = A-8
. = A-9

[shift]
` = M-A-C-S-r
2 = @
3 = "
4 = !
8 = '
9 = $
0 = `
- = %
capslock = \
. = ;
m = :
space = delete

[control+shift]
3 = A-C-g
9 = A-4
0 = A-5
- = A-6
y = A-S-enter
] = A-C-S-end
b = C-S-b
. = A-C-S-pageup

[alt]
y = C-enter

[alt+shift]
w = M-A-C-S-g
e = M-A-C-S-h
r = M-A-C-S-i
y = C-S-enter
a = macro( C-home 80ms C-v 80ms C-S-end 80ms delete )
s = C-delete
d = C-backspace
f = macro( S-end 30ms delete )
c = macro( home 30ms S-end 30ms delete 30ms backspace )
v = macro( S-home 30ms backspace )

[meta]
home = M-volumedown
end = M-volumeup
` = M-A-C-S-n
2 = =
3 = <
4 = >
6 = M-A-C-S-m
8 = &
9 = (
0 = )
- = +
q = 1
w = 2
e = 3
r = 4
t = 5
y = 6
u = 7
i = 8
o = 9
p = 0
capslock = |
a = left
s = up
d = down
f = right
g = middlemouse
h = .
j = end
k = pagedown
l = pageup
; = home
leftshift = M-c
x = *
z = #
c = rightmouse
v = leftmouse
b = ?
m = scrolldown
n = scrollup
, = C-b
. = ~
space = backspace

[meta+control]
# M-1,3,4,5,8 are the only ones suited for app switch shortcuts
2 = C-=
q = M-A-C-S-e
w = M-5
e = C-left
r = C-right
t = A-C-z
u = M-6
i = C-down
o = C-up
p = C-0
capslock = A-C-S-s
a = C-home
s = C-pageup
d = C-pagedown
f = C-end
j = M-1
k = M-2
l = M-3
; = M-4
v = M-A-C-t

[meta+shift]
m = scrollleft
n = scrollright

[meta+alt]
q = kp0
capslock = A-C-S-b

[my_mouse]
q = M-A-C-S-a
w = M-A-C-S-b
e = M-A-C-S-f
r = M-A-C-S-c
t = M-A-C-S-q
g = C-leftmouse
z = A-leftmouse
x = C-S-leftmouse
c = macro( leftmouse 50ms leftmouse 50ms leftmouse )
v = macro( leftmouse 50ms leftmouse )

[my_right_shift]
tab = A-C-6
q = A-C-1
w = A-C-2
e = A-C-3
r = A-C-4
t = A-C-5
a = M-left
s = M-down
d = M-up
f = M-right

[mini_pairs]
w = macro( ` 10ms ` 10ms left )
e = macro( - 10ms - 10ms left )
r = macro( _ 10ms _ 10ms left )
a = macro( < 10ms > 10ms left )
s = macro( [ 10ms ] 10ms left )
d = macro( ( 10ms ) 10ms left )
f = macro( { 10ms } 10ms left )
g = macro( " 10ms " 10ms left )
x = macro( * 10ms * 10ms left )
c = macro( delete 10ms backspace )
v = macro( ' 10ms ' 10ms left )
space = macro( space 10ms space 10ms left )
5 = M-A-C-S-p
6 = M-A-C-S-o
8 = macro( 5 30ms 4 30ms 0 30ms 7 30ms 2 30ms 5 )
9 = M-A-C-S-u
